services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app:cached
    tty: true
    ports:
      - 5173:5173
    command: npm run dev
  setup:
    image: busybox
    depends_on:
      - setup-node_module
  setup-node_module:
    <<: *app
    command: npm ci
